### ISSUE TITLE
can't install v0.1.1

### ISSUE THREAD

**Issue by xwartz** [beplus/fastlane-plugin-versioning_android#16]
Could not find fastlane-plugin-versioning_android-0.1.1 in any of the sources.

The latest version is v0.1.0 on [RubyGems](https://rubygems.org/gems/fastlane-plugin-versioning_android)

**Comment by marcuswu** [comment]
It looks like the tag was created, but no new version was deployed to RubyGems. What needs to happen to get the latest on RubyGems?

**Comment by githubbla** [comment]
resolved by alter 
gem 'fastlane-plugin-versioning_android', git: "https://github.com/beplus/fastlane-plugin-versioning_android.git"

it's bring 0.1.1

**Comment by igorlamos** [comment]
Version `0.1.1` was pushed to [RubyGems](https://rubygems.org/gems/fastlane-plugin-versioning_android).

Can you guys check that it works? Thanks!

**Comment by githubbla** [comment]
removed git, it's updated to 0..1.1
