### ISSUE TITLE
Cannot find the build.gradle and read value

### ISSUE THREAD

**Issue by NinjaRat84** [beplus/fastlane-plugin-versioning_android#5]
Somehow it cannot find the build.gradle file...

```
------------------------------
--- Step: default_platform ---
------------------------------
Driving the lane 'android version' 🚀
--------------------------------------
--- Step: android_get_version_code ---
--------------------------------------
An exception occured while reading gradle file: No such file or directory @ rb_sysopen - /Users/<me>/Application/MyAoo/app/build.gradle

```
But when I take the exact path printed in the terminal, it's found...
Using fastlane 2.139.0

**Comment by FabioTacke** [comment]
Hi @NinjaRat84, as I'm encountering the same problem I wondered if you found a solution to that problem. If so could you please share what you did to make it work?

**Comment by FabioTacke** [comment]
I just found out that in my case a whitespace in the path to the gradle file caused the problem. Actually I confirmed that the fix #6 resolves the issue. So hopefully this gets merged soon.

**Comment by soethan99** [comment]
I'm also facing this error, hope this merge will help me.

**Comment by igorlamos** [comment]
PR #6 was merged! LMK whether it resolved your issue @soethan99.
