### ISSUE TITLE
android_set_version_name sets versionName to empty string

### ISSUE THREAD

**Issue by benomatis** [beplus/fastlane-plugin-versioning_android#9]
#### Fastfile
```ruby
gradle_file = "./android/app/build.gradle"
android_set_version_name(
  gradle_file: gradle_file,
  bump_type: "patch"
)
version_name = android_get_version_name(gradle_file: gradle_file)
puts(version_name) # Returns an empy string
```

#### build.gradle
```
versionName ""
```

While `android_set_version_code(gradle_file: gradle_file)` works perfectly, no problem.

Why?

**Comment by hcyildirim** [comment]
I'm having the same problem, did you solve it?

**Comment by benomatis** [comment]
@hcyildirim I ended up setting the version using [npm version](https://docs.npmjs.com/cli/v7/commands/npm-version) and then taking it from package.json, and explicitly setting it instead of making `android_set_version_name` to it like so:

```ruby
  $package = load_json(json_path: "./package.json")
  $version_number = $package["version"]
  # ...
  android_set_version_name(
    gradle_file: gradle_file,
    version_name: $version_number
  )
```

**Comment by LaVielle** [comment]
Any update on this issue? Running into it now...

**Comment by caioremedio** [comment]
Yep, same issue here. It seems `bump_type` doesn't work anymore.

**Comment by igorlamos** [comment]
Thank you @jgsheffer ... let me check and merge! I'll get back to you ASAP.

**Comment by igorlamos** [comment]
This should be fixed within `v0.1.1`.

**Comment by jgsheffer** [comment]
@igorlamos I don't see version 1.1 in RubyGems.  Is there something else that need to be done in order to pull it in to our project?

**Comment by githubbla** [comment]
anybody plan to update it to 0.1.1 ? still 0.1.0

**Comment by igorlamos** [comment]
Sorry guys, I didn't have too much time to handle it. Let me check what's the status and update to `0.1.1`.

**Comment by igorlamos** [comment]
Version `0.1.1` was pushed to [RubyGems](https://rubygems.org/gems/fastlane-plugin-versioning_android).

**Comment by githubbla** [comment]
thanks, i fixed by adding direct git
cat Pluginfile 
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-versioning_android', git: "https://github.com/beplus/fastlane-plugin-versioning_android.git"
gem 'fastlane-plugin-telegram'
gem 'fastlane-plugin-increment_version_code'
